### PR TITLE
Fix compiler issues / replace std::sin with ImSin ... / Add IMPLOT3D_…

### PR DESCRIPTION
**Pull request by Lumengine**
…API on ImPlot3DBox + ImPlot3DPoint

### CODE REVIEW

**Comment by Lumengine** [comment]
Anything you need from me to complete the PR ?

**Comment by brenocq** [comment]
Hey @Lumengine,

Sorry for the delay in reviewing your PR. I've been traveling recently and haven't had much time with my computer. Your changes look awesome, thank you for taking the time to write them! Once I'm back at my computer, building and merging your code will be my top priority 😬

**Review by brenocq — APPROVED** [review]
Hi @Lumengine,  

I just tested your changes locally, and the reduction in warnings is awesome! When compiling with `-Wall -Wextra -Wpedantic -Wshadow -Wconversion` (Clang 18.1.8), the number of warnings dropped from **1116** to **1042**. It's also great to see all the unnecessary `std::` removed – thank you for that!  

I'm planning to integrate a static code analyzer and enable `-Werror` in the example build to catch these issues earlier. Sorry for the delay in merging your PR — I'll make an effort to get them reviewed and merged faster moving forward.  

If you're interested in contributing more to ImPlot3D, I'm putting together a list of features in the roadmap [here](https://github.com/brenocq/implot3d/discussions/categories/features-and-improvements). Feel free to add more feature ideas there!

I also added [a contributing section](https://github.com/brenocq/implot3d?tab=readme-ov-file#-contributing) to the README to better organize contributions.  

Thanks again for the amazing PR! ❤️

**Comment by Lumengine** [comment]
Thank you for approving ! 
Of course if I have some new ideas of 3d plotting functionalities, I'll let you know in the features sections ! Thanks again for your work !

**Pull request merged**
